# Generated by Django 3.1.3 on 2021-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210119_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='year',
            field=models.DateField(),
        ),
    ]
